[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x", "openssl", "curl"]

[phases.install]
cmds = ["./notify.sh INSTALL pnpm i --frozen-lockfile"]

[phases.build]
cmds = [
    "./notify.sh PRISMA pnpm --filter fan-forge exec prisma generate",
    "./notify.sh BUILD pnpm --filter fan-forge run build"
]

[start]
cmd = "./notify.sh RUNTIME pnpm --filter fan-forge start"
